FROM bioconductor/bioconductor_docker:RELEASE_3_11

MAINTAINER Jonas Schulte-Schrepping

# This will make apt-get install without question
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils \
    	    	       libudunits2-dev \
		       libhdf5-dev \
		       libgdal-dev \
		       gdal-bin \
		       proj-bin \
		       libproj-dev \
		       libgsl-dev \
		       libxml2 \
		       libxml2-dev \
		       libigraph0-dev \
		       zlib1g-dev \
		       libtool \
		       bison \
		       flex \
		       automake \
		       autoconf \
		       libpng*-dev \
		       libglpk-dev \
		       xorg \
		       libx11-dev \
		       libglu1-mesa-dev \
		       libfreetype*-dev \
		       p7zip \
		       build-essential \
		       libssl-dev \
		       libffi-dev \
		       libxslt1-dev \
		       python3 \
		       python-dev \
		       python3-dev \
		       python3-pip \
		       libxt-dev \
		       libgtk2.0-dev \
		       libcairo2-dev \
		       xvfb \
		       xauth \
		       xfonts-base

# update pip
RUN pip install --upgrade pip
RUN pip3 install --upgrade pip

# install wheel
RUN pip install wheel

# install umap-learn
RUN pip3 install numpy==1.19.1
RUN pip3 install scipy==1.5.2
RUN pip3 install python-igraph==0.8.2

RUN pip install jupyterlab==2.2.8
## https://github.com/jupyterlab/jupyterlab-toc

## x means 12 here
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

RUN jupyter labextension install @jupyterlab/toc

RUN R -e 'install.packages("devtools")'
RUN R -e 'install.packages("pkgbuild")'

RUN R -e 'devtools::install_version("IRkernel", version = "1.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
RUN R -e 'IRkernel::installspec(name = "R-MAGeCKFlute-1.8.0", displayname = "R-4.0.2", user = FALSE)'

# install bioc packages
#ADD install_bioc.R /tmp/
#RUN R -f /tmp/install_bioc.R
RUN R -e 'devtools::install_version("BiocGenerics", version="0.34.0", repos=c("https://bioconductor.org/packages/3.11/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'
RUN R -e 'devtools::install_version("MAGeCKFlute", version="1.8.0", repos=c("https://bioconductor.org/packages/3.11/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'
RUN R -e 'devtools::install_github("daattali/ggExtra")'
RUN wget https://bioconductor.org/packages/3.9/bioc/src/contrib/Archive/MAGeCKFlute/MAGeCKFlute_1.4.2.tar.gz
RUN R CMD INSTALL MAGeCKFlute_1.4.2.tar.gz
RUN rm MAGeCKFlute_1.4.2.tar.gz

## Set a default user. Available via runtime flag `--user docker`
## Add user to 'staff' group, granting them write privileges to /usr/local/lib/R/site.library
## User should also have & own a home directory (for rstudio or linked volumes to work properly).
RUN useradd --create-home --shell /bin/bash docker \
        #&& mkdir /home/docker \
        && chown docker:docker /home/docker \
        && addgroup docker staff
#https://stackoverflow.com/questions/27701930/how-to-add-users-to-docker-container
RUN echo 'docker:docker4bix' | chpasswd


WORKDIR /home/docker/
USER docker
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /home/docker/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh
ENV PATH=${PATH}:/home/docker/miniconda3/bin/
RUN conda --version
RUN . /home/docker/miniconda3/etc/profile.d/conda.sh  && conda activate base && \
    conda install -y -c conda-forge mamba==0.5.1 && \
    mamba install -y -c bioconda mageck==0.5.9.4

RUN conda config --add channels defaults && conda config --add channels bioconda && conda config --add channels conda-forge &&  mamba install -y  mageck-vispr==0.5.4
RUN mamba install -y -c conda-forge ipykernel==5.3.4
RUN ipython kernel install --user --name=mageck

USER docker

